export type Tool = {
  name: string;
  slug: string;
  summary: string;
  category: string;
  seoContent: string;
  implemented: boolean;
};

const allTools: Tool[] = [
  {
    name: "JWT Decoder",
    slug: "jwt-decoder",
    summary: "Decode JWT header and payload instantly with validation feedback.",
    category: "Developer",
    seoContent:
      "Use this JWT decoder to inspect token claims, troubleshoot auth flows, and validate payload structure in seconds.",
    implemented: true,
  },
  {
    name: "JSON Formatter",
    slug: "json-formatter",
    summary: "Format, minify, and validate JSON data accurately.",
    category: "Developer",
    seoContent:
      "Our JSON formatter helps developers debug APIs and clean payloads with pretty-print and minify support.",
    implemented: true,
  },
  {
    name: "Base64 Encoder Decoder",
    slug: "base64-encoder-decoder",
    summary: "Encode and decode Base64 strings with UTF-8 support.",
    category: "Developer",
    seoContent:
      "Convert plain text to Base64 and back using a safe browser-based utility designed for modern workflows.",
    implemented: true,
  },
  {
    name: "URL Encoder Decoder",
    slug: "url-encoder-decoder",
    summary: "Encode and decode URL strings for web-safe transport.",
    category: "Developer",
    seoContent:
      "Prepare query parameters correctly and decode encoded URLs quickly using this reliable tool.",
    implemented: true,
  },
  {
    name: "UUID Generator",
    slug: "uuid-generator",
    summary: "Generate secure UUIDs for IDs, records, and sessions.",
    category: "Developer",
    seoContent:
      "Generate RFC-style unique identifiers for distributed systems, database keys, and client-side workflows.",
    implemented: true,
  },
  {
    name: "Password Generator",
    slug: "password-generator",
    summary: "Create strong customizable passwords for better security.",
    category: "Security",
    seoContent:
      "Build secure passwords with configurable length and character options to improve account safety.",
    implemented: true,
  },
  {
    name: "Hash Generator",
    slug: "hash-generator",
    summary: "Generate SHA-256 hashes directly in your browser.",
    category: "Security",
    seoContent:
      "Hash sensitive strings with SHA-256 for integrity checks and secure comparison workflows.",
    implemented: true,
  },
  {
    name: "Unix Timestamp Converter",
    slug: "unix-timestamp-converter",
    summary: "Convert Unix timestamps to human-readable date/time.",
    category: "Developer",
    seoContent:
      "Convert epoch values to readable dates and back for logging, analytics, and API debugging.",
    implemented: true,
  },
  {
    name: "Color Converter",
    slug: "color-converter",
    summary: "Convert HEX color values into RGB format instantly.",
    category: "Design",
    seoContent:
      "Transform HEX codes into RGB values for design systems, CSS workflows, and front-end consistency.",
    implemented: true,
  },
  {
    name: "Slug Generator",
    slug: "slug-generator",
    summary: "Create clean SEO-friendly URL slugs from any title.",
    category: "SEO",
    seoContent:
      "Generate readable URL slugs that improve clarity, sharing, and search engine optimization.",
    implemented: true,
  },
  {
    name: "ROI Calculator",
    slug: "roi-calculator",
    summary: "Model investment returns with monthly and annual projections.",
    category: "Finance",
    seoContent: "Estimate return on investment to evaluate campaign and product profitability.",
    implemented: false,
  },
  {
    name: "Invoice Generator",
    slug: "invoice-generator",
    summary: "Create clean professional invoices ready for PDF export.",
    category: "Business",
    seoContent: "Produce polished invoices quickly with structured fields and clear totals.",
    implemented: false,
  },
  {
    name: "Loan Repayment Planner",
    slug: "loan-repayment-planner",
    summary: "Estimate monthly payments and total interest over time.",
    category: "Finance",
    seoContent: "Plan repayment schedules with practical amortization insights.",
    implemented: false,
  },
  {
    name: "Profit Margin Analyzer",
    slug: "profit-margin-analyzer",
    summary: "Measure gross and net margin performance accurately.",
    category: "Business",
    seoContent: "Track margin health and identify opportunities to increase profitability.",
    implemented: false,
  },
  {
    name: "SEO Meta Builder",
    slug: "seo-meta-builder",
    summary: "Generate optimized titles and descriptions for search.",
    category: "SEO",
    seoContent: "Craft metadata aligned with intent and click-through optimization.",
    implemented: false,
  },
  {
    name: "Word Counter",
    slug: "word-counter",
    summary: "Count words, characters, and reading time instantly.",
    category: "Writing",
    seoContent: "Measure content length quickly for publishing standards.",
    implemented: false,
  },
  {
    name: "Case Converter",
    slug: "case-converter",
    summary: "Convert text to upper, lower, title, and sentence case.",
    category: "Writing",
    seoContent: "Normalize text casing for content and coding workflows.",
    implemented: false,
  },
  {
    name: "CSV to JSON",
    slug: "csv-to-json",
    summary: "Convert CSV rows to structured JSON output.",
    category: "Developer",
    seoContent: "Transform tabular exports into JSON for modern APIs.",
    implemented: false,
  },
  {
    name: "JSON to CSV",
    slug: "json-to-csv",
    summary: "Convert JSON arrays to CSV format quickly.",
    category: "Developer",
    seoContent: "Export structured JSON datasets into spreadsheet-ready CSV.",
    implemented: false,
  },
  {
    name: "HTTP Header Inspector",
    slug: "http-header-inspector",
    summary: "Review and parse HTTP header blocks cleanly.",
    category: "Developer",
    seoContent: "Inspect request and response headers for diagnostics.",
    implemented: false,
  },
  {
    name: "Regex Tester",
    slug: "regex-tester",
    summary: "Test regular expressions against sample text.",
    category: "Developer",
    seoContent: "Validate regex patterns before shipping to production.",
    implemented: false,
  },
  {
    name: "HTML Minifier",
    slug: "html-minifier",
    summary: "Reduce HTML size for faster page delivery.",
    category: "Performance",
    seoContent: "Improve load speed by optimizing HTML output.",
    implemented: false,
  },
  {
    name: "CSS Minifier",
    slug: "css-minifier",
    summary: "Compress CSS code for performance gains.",
    category: "Performance",
    seoContent: "Minify CSS files to reduce network payload.",
    implemented: false,
  },
  {
    name: "JavaScript Minifier",
    slug: "javascript-minifier",
    summary: "Minify JavaScript source safely for deployment.",
    category: "Performance",
    seoContent: "Shrink JavaScript bundles for better performance scores.",
    implemented: false,
  },
  {
    name: "Image Size Estimator",
    slug: "image-size-estimator",
    summary: "Estimate image dimensions and file impact quickly.",
    category: "Design",
    seoContent: "Plan media assets based on size and speed budgets.",
    implemented: false,
  },
  {
    name: "Reading Time Estimator",
    slug: "reading-time-estimator",
    summary: "Estimate reading duration for content pieces.",
    category: "Writing",
    seoContent: "Improve UX with accurate reading-time indicators.",
    implemented: false,
  },
  {
    name: "Keyword Density Checker",
    slug: "keyword-density-checker",
    summary: "Analyze keyword usage frequency in your content.",
    category: "SEO",
    seoContent: "Balance keyword frequency for relevance and readability.",
    implemented: false,
  },
  {
    name: "Meta Tag Preview",
    slug: "meta-tag-preview",
    summary: "Preview search snippet titles and descriptions.",
    category: "SEO",
    seoContent: "Simulate SERP presentation for improved click potential.",
    implemented: false,
  },
  {
    name: "Open Graph Generator",
    slug: "open-graph-generator",
    summary: "Build social meta tags for link previews.",
    category: "SEO",
    seoContent: "Create Open Graph tags for better social sharing.",
    implemented: false,
  },
  {
    name: "Email Subject Line Grader",
    slug: "email-subject-line-grader",
    summary: "Score subject lines for clarity and impact.",
    category: "Marketing",
    seoContent: "Improve open rates with stronger subject line structure.",
    implemented: false,
  },
  {
    name: "UTM Builder",
    slug: "utm-builder",
    summary: "Generate campaign tracking URLs with UTM tags.",
    category: "Marketing",
    seoContent: "Track marketing channels with standardized UTM links.",
    implemented: false,
  },
  {
    name: "Break Even Calculator",
    slug: "break-even-calculator",
    summary: "Calculate break-even points for products and services.",
    category: "Finance",
    seoContent: "Understand when revenue covers costs and drives profit.",
    implemented: false,
  },
  {
    name: "Gross Margin Calculator",
    slug: "gross-margin-calculator",
    summary: "Compute gross margin percentage from sales data.",
    category: "Finance",
    seoContent: "Monitor product profitability with fast margin analysis.",
    implemented: false,
  },
  {
    name: "Net Profit Calculator",
    slug: "net-profit-calculator",
    summary: "Calculate net profit from revenue and expenses.",
    category: "Finance",
    seoContent: "Estimate bottom-line performance quickly and accurately.",
    implemented: false,
  },
  {
    name: "Commission Calculator",
    slug: "commission-calculator",
    summary: "Calculate sales commission by rate and tiers.",
    category: "Finance",
    seoContent: "Forecast payouts and incentives using commission logic.",
    implemented: false,
  },
  {
    name: "VAT Calculator",
    slug: "vat-calculator",
    summary: "Add or remove VAT from any amount instantly.",
    category: "Finance",
    seoContent: "Compute VAT-inclusive and VAT-exclusive prices fast.",
    implemented: false,
  },
  {
    name: "Discount Calculator",
    slug: "discount-calculator",
    summary: "Calculate discount amounts and final price.",
    category: "Commerce",
    seoContent: "Evaluate promotional pricing with precision.",
    implemented: false,
  },
  {
    name: "Markup Calculator",
    slug: "markup-calculator",
    summary: "Compute markup percentage and final pricing.",
    category: "Commerce",
    seoContent: "Set profitable selling prices based on markup goals.",
    implemented: false,
  },
  {
    name: "Percentage Calculator",
    slug: "percentage-calculator",
    summary: "Solve common percentage equations quickly.",
    category: "Math",
    seoContent: "Handle percentage increase, decrease, and share calculations.",
    implemented: false,
  },
  {
    name: "Unit Converter",
    slug: "unit-converter",
    summary: "Convert units across length, weight, and volume.",
    category: "Math",
    seoContent: "Convert measurement units for technical and daily tasks.",
    implemented: false,
  },
  {
    name: "Speed Converter",
    slug: "speed-converter",
    summary: "Convert speed values between km/h, mph, and m/s.",
    category: "Math",
    seoContent: "Switch speed units accurately for analysis and reporting.",
    implemented: false,
  },
  {
    name: "BMI Calculator",
    slug: "bmi-calculator",
    summary: "Calculate body mass index from height and weight.",
    category: "Health",
    seoContent: "Estimate BMI with a simple and accurate formula.",
    implemented: false,
  },
  {
    name: "Calorie Needs Estimator",
    slug: "calorie-needs-estimator",
    summary: "Estimate daily calorie requirements by profile.",
    category: "Health",
    seoContent: "Calculate baseline calorie targets for planning.",
    implemented: false,
  },
  {
    name: "Mortgage Calculator",
    slug: "mortgage-calculator",
    summary: "Estimate mortgage payments and total borrowing cost.",
    category: "Finance",
    seoContent: "Compare mortgage scenarios before final decisions.",
    implemented: false,
  },
  {
    name: "Compound Interest Calculator",
    slug: "compound-interest-calculator",
    summary: "Project growth with compounding over time.",
    category: "Finance",
    seoContent: "Forecast long-term gains with compound growth models.",
    implemented: false,
  },
  {
    name: "Savings Goal Planner",
    slug: "savings-goal-planner",
    summary: "Plan monthly savings to hit target amounts.",
    category: "Finance",
    seoContent: "Build practical savings plans with time-based goals.",
    implemented: false,
  },
  {
    name: "Debt Snowball Planner",
    slug: "debt-snowball-planner",
    summary: "Organize debt payoff order and progress.",
    category: "Finance",
    seoContent: "Visualize debt reduction strategy using snowball methods.",
    implemented: false,
  },
  {
    name: "Time Zone Converter",
    slug: "time-zone-converter",
    summary: "Convert meeting times across global zones.",
    category: "Productivity",
    seoContent: "Coordinate remote schedules with timezone precision.",
    implemented: false,
  },
  {
    name: "Pomodoro Timer",
    slug: "pomodoro-timer",
    summary: "Run focus sessions with timed intervals.",
    category: "Productivity",
    seoContent: "Boost concentration with structured work-rest cycles.",
    implemented: false,
  },
  {
    name: "Task Priority Matrix",
    slug: "task-priority-matrix",
    summary: "Prioritize tasks by urgency and importance.",
    category: "Productivity",
    seoContent: "Organize workloads with a clear decision framework.",
    implemented: false,
  },
  {
    name: "Meeting Agenda Builder",
    slug: "meeting-agenda-builder",
    summary: "Generate structured meeting agendas quickly.",
    category: "Productivity",
    seoContent: "Run efficient meetings with concise agenda templates.",
    implemented: false,
  },
  {
    name: "Character Counter",
    slug: "character-counter",
    summary: "Count characters for social and SEO limits.",
    category: "Writing",
    seoContent: "Stay within platform limits for titles and captions.",
    implemented: false,
  },
  {
    name: "Headline Analyzer",
    slug: "headline-analyzer",
    summary: "Assess headlines for clarity and CTR potential.",
    category: "Marketing",
    seoContent: "Improve headline impact with practical scoring cues.",
    implemented: false,
  },
  {
    name: "Link Extractor",
    slug: "link-extractor",
    summary: "Extract all links from pasted HTML snippets.",
    category: "Developer",
    seoContent: "Audit outbound links and references at scale.",
    implemented: false,
  },
  {
    name: "Word Frequency Analyzer",
    slug: "word-frequency-analyzer",
    summary: "Analyze common terms in text content.",
    category: "Writing",
    seoContent: "Find recurring words to improve content balance.",
    implemented: false,
  },
  {
    name: "Sitemap Validator",
    slug: "sitemap-validator",
    summary: "Validate XML sitemap syntax and structure.",
    category: "SEO",
    seoContent: "Verify sitemap quality to support indexation.",
    implemented: false,
  },
  {
    name: "Robots.txt Tester",
    slug: "robots-txt-tester",
    summary: "Test robots directives for crawl behavior.",
    category: "SEO",
    seoContent: "Ensure correct crawler access with robots.txt checks.",
    implemented: false,
  },
];

export const tools: Tool[] = allTools.slice(0, 50);

export function getToolBySlug(slug: string) {
  return tools.find((tool) => tool.slug === slug) ?? null;
}
